version: '3.8'

services:
  payload:
    image: node:22.20.0-alpine
    working_dir: /app
    command: sh -c "npm install && npm run build && npm start"
    environment:
      - NODE_ENV=production
      - DATABASE_URI=mongodb://mongo:27017/recipes
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - CRON_SECRET=${CRON_SECRET}
      - PREVIEW_SECRET=${PREVIEW_SECRET}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    command: --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
